services:
  - type: web
    name: cargo-assign
    env: java
    plan: free
    rootDir: .
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Dserver.port=$PORT -jar target/CargoAssign-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        value: "86400000"
