services:
  - type: web
    name: cargo-assign
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_URL
        value: "jdbc:postgresql://dpg-d6kplu3h46gs73d3u9i0-a:5432/cargo_assign_db_6v2e"
      - key: DB_USERNAME
        value: "cargo_assign_db_6v2e_user"
      - key: DB_PASSWORD
        value: "G6jWUNxZq69P2f0WxUaDnjgnooOsGrEx"
      - key: DB_DRIVER
        value: "org.postgresql.Driver"
      - key: HIBERNATE_DIALECT
        value: "org.hibernate.dialect.PostgreSQLDialect"
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        value: "86400000"

