spring.application.name=Cargo Assign

# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6kplu3h46gs73d3u9i0-a:5432/cargo_assign_db_6v2e}
spring.datasource.username=${DB_USERNAME:cargo_assign_db_6v2e_user}
spring.datasource.password=${DB_PASSWORD:G6jWUNxZq69P2f0WxUaDnjgnooOsGrEx}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.enabled=true

# ===============================
# External Services
# ===============================
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY:}

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:local-dev-secret-key-please-change}

